import React, { useState } from "react";
import { XIcon, InboxIcon } from "@heroicons/react/outline";
import Head from "next/head";
import Link from "next/link";
import TopBar from "../../components/TopBar";
import { classNames } from "../../utilities/css";

const tabs = [
  { name: "購物明細", href: "#", current: true },
  { name: "下次再買清單", href: "#", current: false },
];

const books = [
  {
    id: 1,
    name: "圖像資訊表達課",
    cover_url:
      "https://s3.ap-northeast-1.amazonaws.com/s3.sat/course/1648608896_re-lab%E8%A6%96%E8%A6%BA_%E5%B7%A5%E4%BD%9C%E5%8D%80%E5%9F%9F%201.jpg",
    price: 500,
  },
  {
    id: 2,
    name: "Redis 實戰手冊",
    cover_url:
      "https://s3.ap-northeast-1.amazonaws.com/s3.sat/course/1647924019_%E5%8A%89%E5%8D%9A%E4%BB%81%EF%BD%9C%E4%B8%BB%E8%A6%96%E8%A6%BA%E6%8E%92%E7%89%88%20_%20872%20x%20480_v7.jpg",
    price: 369,
  },
];

export default function Cart() {
  const tabsMarkup = (
    <div className="block">
      <div className="border-b border-gray-200">
        <nav className="-mb-px flex" aria-label="Tabs">
          {tabs.map((tab) => (
            <a
              key={tab.name}
              href={tab.href}
              className={classNames(
                tab.current
                  ? "border-gray-900 text-gray-900"
                  : "border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300",
                "w-1/4 py-4 px-1 text-center border-b-[3px] font-medium text-sm"
              )}
              aria-current={tab.current ? "page" : undefined}
            >
              {tab.name}
            </a>
          ))}
        </nav>
      </div>
    </div>
  );

  return (
    <div>
      <Head>
        <title>購物車</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-gray-light">
        <TopBar />
        <div className="flex min-h-screen h-full">
          <div className="max-w-5xl mx-auto w-full px-2 sm:px-6 lg:px-8">
            <div className="-mx-4 mt-10 sm:-mx-6 md:mx-0 flex flex-col">
              {tabsMarkup}
              <div className="mb-5 flex items-center shadow overflow-hidden rounded h-13 text-md bg-[#ffffff] text-gray-800 px-5">
                <div className="flex-[17_1_0%]">商品名稱</div>
                <div className="flex-[8_1_0%]">小計</div>
                <div className="flex-[5_1_0%]">操作</div>
              </div>
              <div className="mb-10 bg-[#ffffff] shadow rounded divide-y divide-gray-300">
                {books.map((book) => (
                  <div className="flex items-center py-4 px-5" key={book.id}>
                    <div className="flex flex-[17_1_0%]">
                      <img
                        className="object-cover w-full h-96 md:h-auto md:w-28"
                        src={book.cover_url}
                        alt={book.name}
                      />
                      <div className="pl-4 text-gray-700 font-semibold">
                        {book.name}
                      </div>
                    </div>
                    <div className="flex-[8_1_0%]">NT${book.price}</div>
                    <div className="flex flex-col flex-[5_1_0%] text-sm">
                      <div className="flex items-center space-x-1 text-gray-600">
                        <span>
                          <XIcon className="w-4 h-4" />
                        </span>
                        <span>移除</span>
                      </div>
                      <div className="flex items-center space-x-1 mt-2 text-gray-600">
                        <span>
                          <InboxIcon className="w-4 h-4" />
                        </span>
                        <span>下次再買</span>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
              <div className="bg-[#ffffff] shadow rounded px-5">
                <div className="flex items-center py-3">
                  <div className="flex-[5_1_0%] flex items-center">
                    <div>
                      商品小計: &nbsp;
                      <span className="font-medium text-base text-red-600">
                        NT$869
                      </span>
                    </div>
                    <div className="px-4">-</div>
                    <div>
                      折扣: &nbsp;
                      <span className="font-medium text-base text-red-600">
                        NT$0
                      </span>
                    </div>
                  </div>
                  <div className="flex-[7_1_0%] flex items-center justify-end">
                    <div className="pr-6">
                      總金額(2 項商品): &nbsp;
                      <span className="font-semibold text-2xl text-red-600">
                        NT$869
                      </span>
                    </div>
                    <Link href={`/checkout`}>
                      <a
                        className="btn w-48 bg-slate-900 shadow-1 transition text-white font-bold border border-solid border-transparent
          hover:bg-slate-700 focus:bg-slate-700"
                      >
                        結帳
                      </a>
                    </Link>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
