import React from "react";
import Head from "next/head";
import TopBar from "../../components/TopBar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>首頁</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <TopBar />
        <div className="flex min-h-screen h-full">
          <div className="flex-auto">
            <main>Home</main>
            <footer>Footer</footer>
          </div>
        </div>
      </div>

      <style global jsx>{`
        body {
          background: rgb(246, 246, 247);
        }
      `}</style>
    </div>
  );
}
