import React, { useState } from "react";
import Head from "next/head";
import TopBar from "../../components/TopBar";
import Catalog from "../../components/Catalog";
import { useForm } from "react-hook-form";
import TextField from "../../components/TextField";

export default function Home() {
  const { register, handleSubmit } = useForm();
  return (
    <div>
      <Head>
        <title>首頁</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <TopBar />
        <div className="flex min-h-screen h-full">
          <div className="container max-w-[63rem] mx-auto px-5 pt-10">
            <Catalog />
            <TextField
              id="invoice_title"
              type="text"
              label="發票抬頭"
              error=""
              register={register}
            />
          </div>
        </div>
      </div>
    </div>
  );
}
