import React, { useState } from "react";
import Head from "next/head";
import TopBar from "../../components/TopBar";
import TiptapEditor from "../../components/TiptapEditor";

export default function Home() {
  return (
    <div>
      <Head>
        <title>首頁</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <TopBar />
        <div className="flex min-h-screen h-full">
          <div className="mt-20 ml-20 w-full">
            <TiptapEditor />
          </div>
        </div>
      </div>
    </div>
  );
}
