import React, { useState } from "react";
import Head from "next/head";
import TopBar from "../../components/TopBar";
import Catalog from "../../components/Catalog";
import CategoryFilter from "./components/CategoryFilter";
import SecondCategoryFilter from "./components/SecondCategoryFilter";

export default function Explore() {
  const dividerMarkup = (
    <div className="w-full border-t border-gray-300 mb-6" />
  );
  return (
    <div>
      <Head>
        <title>探索</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <TopBar />
        <div className="flex min-h-screen h-full">
          <div className="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
            <div className="flex my-10">
              <div className="flex-[0_0_auto] w-48 pr-8">
                <CategoryFilter />
              </div>
              <div className="flex-1 flex-col px-8">
                <SecondCategoryFilter />
                <Catalog />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
