import React from "react";
import Head from "next/head";
import TopBar from "../../components/TopBar";

import TableOfContent from "./components/TableOfContent";
import Author from "./components/Author";
import BookTitle from "./components/BookTitle";
import TakeawaySkill from "./components/TakeawaySkill";
import AboutBook from "./components/AboutBook";
import BookCard from "./components/BookCard";

export default function Book() {
  return (
    <div>
      <Head>
        <title>一生都能好好記憶</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <TopBar />
        <BookTitle />
        <div className="w-full">
          <div className="max-w-5xl mx-auto py-10">
            <div className="flex flex-col sm:flex-row">
              <div className="flex flex-col lg:mr-16 space-y-9 max-w-[calc(100%_-_theme('spacing.90'))]">
                <TakeawaySkill />
                <AboutBook />
                <TableOfContent />
                <Author />
              </div>
              <div className="flex">
                <BookCard />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
